FROM php:8.1-apache

# Instalar extensiones de MySQL para PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql \
 && docker-php-ext-enable mysqli pdo_mysql

# Opcional: habilitar módulo rewrite de Apache
RUN a2enmod rewrite
