CREATE DATABASE IF NOT EXISTS web2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE web2;
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);